### PR TITLE
Migrate to GitHub Actions

### LINKED ISSUE #154: Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by core-man**
Fixes #154.

### CODE REVIEW

**Comment by core-man** [comment]
See https://github.com/gmt-china/gmt-china.org/pull/156/checks?check_run_id=2673508020:

> Error: Error building site: "/home/runner/work/gmt-china.org/gmt-china.org/content/blog/2016-04-06-gmt-china-community-founded/index.md:53:1": failed to extract shortcode: template for shortcode "alert" not found

I think it may be related to the theme which is updated two years ago (https://github.com/gmt-china/gmt-china.org/commit/4fa10d19806cb8786b67da5c67260ff512203a99)

**Comment by seisman** [comment]
> I think it may be related to the old theme (`v4.3.1`) which is updated two years ago ([4fa10d1](https://github.com/gmt-china/gmt-china.org/commit/4fa10d19806cb8786b67da5c67260ff512203a99)). We may want to update to the latest theme in a separate PR, but I may need more time to work on it and potentially need your help @seisman

Please do it in separate PRs.

**Comment by core-man** [comment]
> 我看了一下升级指南，现在的版本是v4，最新的是v5，版本之间的差别太大了。我试着基于目前进行升级，发现难度太大，要做的事太多了，配置文件的格式完全不一样。还不如重做。
> 
> 我准备用v5的主题，把现在的内容手工迁移过来。做完之后我先传到自己的仓库中，你们先看看效果

Thanks for your thought, but I'd like to suggest you focus on the GMT_Docs. The website theme will be updated by several PRs in this repo later. You could help when we begin to work on it or you could submit several small PRs first.

**Comment by CovMat** [comment]
> > 我看了一下升级指南，现在的版本是v4，最新的是v5，版本之间的差别太大了。我试着基于目前进行升级，发现难度太大，要做的事太多了，配置文件的格式完全不一样。还不如重做。
> > 我准备用v5的主题，把现在的内容手工迁移过来。做完之后我先传到自己的仓库中，你们先看看效果
> 
> Thanks for your thought, but I'd like to suggest you focus on the GMT_Docs. The website theme will be updated by several PRs in this repo later. You could help when we begin to work on it or you could submit several small PRs first. I think we may want to update it instead of re-writing it.
> 
> BTW, I migrated our group website from v4.8 to v5.2 yesterday (see [MIGG-NTU/academic#16](https://github.com/MIGG-NTU/academic/pull/16)).

有道理，好

**Comment by core-man** [comment]
@seisman Could we merge this PR first before we update to theme v5.2 so that GitHub Actions can be used.

**Comment by seisman** [comment]
Are the changes to images necessary?

**Comment by core-man** [comment]
> Are the changes to images necessary?

It seems that they are not committed in the master branch. I guess it may be related to #148 and/or #149. If I don't revert the changes, ci will report error.

**Comment by seisman** [comment]
> > Are the changes to images necessary?
> 
> It seems that they are not committed in the master branch. I guess it may be related to #148 and/or #149. If I don't revert the changes, ci will report error.
> 
> See [gmt-china/gmt-china.org/runs/2673473286?check_suite_focus=true](https://github.com/gmt-china/gmt-china.org/runs/2673473286?check_suite_focus=true)
> 
> > Error: Error building site: process: readAndProcessContent: walk: Readdir: decorate: lstat /home/runner/work/gmt-china.org/gmt-china.org/content/example/ex024/����: no such file or directory

https://stackoverflow.com/questions/56834754/cloning-a-git-project-status-of-images-is-suddenly-turned-to-modified

**Comment by seisman** [comment]
FYI, changes in #148 is reverted and now the CI pass. You can do the github actions migration now. It may be easier for you to restart a new PR.

**Comment by core-man** [comment]
> FYI, changes in #148 is reverted and now the CI pass. You can do the github actions migration now. It may be easier for you to restart a new PR.

Close this PR?

**Pull request closed without merging**
